
#-----------------------------------------------#
#             Bombastic Projectiles             #
#                                               #
#                  Sintax Labs                  #
#-----------------------------------------------#

#-----------------------------------------------#
#                 General Options               #
#-----------------------------------------------#

require-Permission: false
#If true, Permissions and Features must be both granted/enabled.
#Permissions do not limit mobs if mob-explode toggles are enabled.

impact-Custom: false
#Allows custom explosive impact for each projectile.
#If enabled, impact-all will be ignored. Vice Versa.

impact-All: 5
#Requires impact-Custom to be false.
#0 = No Impact
#127 = Max Impact



#-----------------------------------------------#
#               Explosion Features              #
#-----------------------------------------------#

toggle-Fire: false
#Similar to Ghast fireball explosions.

toggle-BreakBlocks: true
#NOTE: To prevent block-damage in WorldGuard Regions, set other-explosions to false in your Region Flags.
#/rg info regionName then Flags.

toggle-HurtMobs: false
toggle-HurtPlayer: false
#Whether explosive damage should harm mobs or players.



#-----------------------------------------------#
#                   Mob Options                 #
#-----------------------------------------------#

mobs-Explode-Entities: false
mobs-Explode-Blocks: false
#Mobs can trigger explosions if their corresponding item is enabled.
#They are still limited by toggle-BreakBlocks and hurting other mobs/players.

Mob-Impact: false
#If false, mobs will use custom impact levels REGARDLESS of impact-Custom being enabled/disabled.
Mob-Impact-Damage: 2
#Custom Explosive Damage from Mobs



#-----------------------------------------------#
#               Projectile Toggles              #
#-----------------------------------------------#
Egg: false
Arrow: true
Potion: false
Trident: false
Snowball: false
ExpBottle: false
Enderpearl: false
FishingBobber: false


#-----------------------------------------------#
#               Projectile Impacts              #
#                                               #
#           MUST ENABLE impact-Custom           #
#-----------------------------------------------#

Egg-Impact: 2
Arrow-Impact: 5
Potion-Impact: 3
Trident-Impact: 10
Snowball-Impact: 2
ExpBottle-Impact: 3
Enderpearl-Impact: 0
FishingBobber-Impact: 1


#-----------------------------------------------#
#             Miscellaneous Toggles             #
#-----------------------------------------------#

trident-Teleport: false
#Fixes issue of tridents getting stuck in mid-air.
trident-TP-Message: true
#Lets the shooter know their trident was teleported back to them. Only works if trident-Teleport is enabled.

verbose: false
#Not recommended for public servers.
#Used for debugging.