name: BombasticProjectiles
version: '1.0.7'
main: me.sintaxlabs.bombasticProjectiles1165.main
api-version: '1.16'

permissions:
  bombasticProjectiles.all:
    description: Gives access to all enabled features.
    default: false
    children:
      bombasticProjectiles.projectiles: true
      bombasticProjectiles.breakBlocks: true
      bombasticProjectiles.harmPlayers: true
      bombasticProjectiles.harmMobs: true

  bombasticProjectiles.projectiles:
    description: Gives access to projectiles causing the explosive effect but won't harm.
    default: false
  bombasticProjectiles.breakBlocks:
    description: Gives access to breaking blocks if that's enabled.
    default: false
  bombasticProjectiles.harmPlayers:
    description: Gives access to harming players if that's enabled.
    default: false
  bombasticProjectiles.harmMobs:
    description: Gives access to harming players if that's enabled.
    default: false
  bombasticProjectiles.reload:
    description: Allows user to reload the configuration.
    default: op


commands:
  reloadconfig:
    description: Reloads the BombasticProjectiles config
    usage: /bprojectile <subcommand>
    aliases: [ bprojectile, bombprojectiles, bproject, bombasticprojectiles ]
    permission: bombasticProjectiles.reload